# Generated by Django 4.2.3 on 2023-08-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=models.CharField(
                max_length=7,
                unique=True,
                verbose_name='Цвет тега в формате HEX',
            ),
        ),
    ]
